name        : libxdamage
version     : 1.1.4
release     : 7
source      :
    - http://xorg.freedesktop.org/releases/individual/lib/libXdamage-1.1.4.tar.bz2 : 7c3fe7c657e83547f4822bfde30a90d84524efb56365448768409b77f05355ad
license     :
    - MIT
summary     : X11 damaged region extension library
component   : xorg.library
builddeps   :
    - pkgconfig(damageproto)
    - pkgconfig(xfixes)
    - pkgconfig32(xfixes)
    - pkgconfig(xext)
    - pkgconfig32(xext)
    - pkgconfig(x11)
    - pkgconfig32(x11)
    - glibc-32bit-devel
    - libgcc-32bit
emul32      : yes
optimize    : speed
description : |
    libXdamage provides an X Window System client interface to the DAMAGE extension to the X protocol.
setup      : |
    %configure --prefix=/usr \
               --disable-static
build      : |
    %make
install    : |
    %make_install
