name       : libxdamage
version    : 1.1.5
release    : 12
source     :
    - http://xorg.freedesktop.org/releases/individual/lib/libXdamage-1.1.5.tar.gz : 630ec53abb8c2d6dac5cd9f06c1f73ffb4a3167f8118fdebd77afd639dbc2019
license    :
    - MIT
summary    : X11 damaged region extension library
component  : xorg.library
description: |
    libXdamage provides an X Window System client interface to the DAMAGE extension to the X protocol.
builddeps  :
    - pkgconfig(damageproto)
    - pkgconfig32(xext)
    - pkgconfig32(xfixes)
    - pkgconfig32(x11)
emul32     : yes
optimize   : speed
setup      : |
    %configure --prefix=/usr \
               --disable-static
build      : |
    %make
install    : |
    %make_install
